config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/edit'

  get 'events/update'

  get 'events/delete'

  devise_for :users, controllers: { sessions: "users/sessions" }, :skip => :registrations
  
  
  root to: "events#index"
  resources :events do
    member do
      get 'page'
      get 'edit_page'
    end

    resources :guests do
      member do
        get 'invite'
        post 'create_invite'
      end
    end
    resources :rsvps, except: [ :index ]
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :setup_existing, only: [ :show, :destroy, :invite, :create_invite]
  
  def new
    @guest = User.new
  end
  
  def create
    name = params[:user][:name]
    email = params[:user][:email]
    event_id  = params[:event_id]
    @event = Event.find(event_id)
    @guest = User.find_by(email: email)
    if @guest.nil?
      generated_password = Devise.friendly_token.first(8)
      # @guest = User.new(name: name, email: email, password: generated_password, password_confirmation: generated_password)
      @guest = User.new(guest_params)
      @guest.password = generated_password
      @guest.password_confirmation = generated_password
      if @guest.save
        @event.add_guest(@guest)
        flash[:notice] = 'User was successfully invited!'
        redirect_to event_path(@event)
      else
        render :action => "new"
      end
    else
      # guest already exists
      redirect_to invite_event_guest_path(@event, @guest)
    end
  end
  
  def show
  end
  
  def destroy
    if @guest.events.count > 1
      @event.remove_guest(@guest)
      redirect_to event_path(@event)
    else
      if @guest.destroy
        redirect_to event_path(@event)
      end
    end
  end
  
  def invite
  end
  
  def create_invite
    @event.add_guest(@guest) if !@guest.invited?(@event) 
    redirect_to event_path(@event)
  end
  
  private
  
  def guest_params
    params.require(:user).permit(:name, :email, :address1, :address2, :post_code, :suburb, :number_of_guests, )
  end

  def setup_existing
    @guest = User.find(params[:id])
    @event = Event.find(params[:event_id])
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_guests.html.erb
<tr>
    <td><%= link_to guest.name, event_guest_path(@event, guest) %></td>
    <td><%= guest.email %></td>
    <td><%= guest.address %></td>
    <td class="text-center"><%= guest.number_of_guests %></td>
    <% if guest.rsvp? %>
        <td class="text-center">Yes</td>
    <% else %>
        <td class="text-center">No</td>
    <% end %>
    <td class="text-center"></td>
    <td><%= link_to "Remove", event_guest_path(@event, guest), method: "delete",  data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/guests/invite.html.erb
<h1>Invite Guest</h1>
<p><%= @guest.name %> (<%= @guest.email %>) already exists.</p>
<p>Do you want to add them to the guest list for <%= @event.name %>?</p>
<%= form_for :guest, :url=>create_invite_event_guest_path(@event, @guest) do |f| %>
  <%= f.submit "Add to list", disable_with: 'Add to listing...' %>
<% end %>

app/views/guests/new.html.erb
<div class="row"> 
  <div class="col-md-8 col-md-offset-2">
    <%= render 'layouts/errors', object: @guest %>
    <h2 class="text-center">Add Guest</h2>
    <%= form_for(@guest, :url => {:controller => 'guests', :action => 'create'}, html: { class: "form-horizontal"}) do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: "form-control" %>
            <span id="helpBlock" class="help-block">
              The name on the invitation e.g. Mr and Mrs John Smith, Bob and Mary Jones etc.
            </span>
          </div>
          
        </div>
        <div class="form-group">
          <%= f.label :number_of_guests, "Number of guests on the invite", class: "col-sm-10 control-label" %>
          <div class="col-sm-2">
            <%= f.select :number_of_guests, (1..10), {}, { class: "form-control"} %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.email_field :email, class: "form-control" %>
            <span id="helpBlock" class="help-block">
              Email address of the primary contact. They will use this to RSVP.
            </span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :address1, "Address 1", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :address1, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :address2, "Address 2", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :address2, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :suburb, "Suburb", class: "col-sm-3 control-label" %>
          <div class="col-sm-5">
            <%= f.text_field :suburb, class: "form-control" %>
          </div>
          <%= f.label :post_code, "Post Code", class: "col-sm-2 control-label" %>
          <div class="col-sm-2">
            <%= f.text_field :post_code, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <%= f.submit "Add Guest", :disable_with => 'Saving...', class: "btn btn-primary" %>
          </div>
        </div>
      
    <% end %>  
    <%= debug @guest %>
    
  </div>
</div>

app/views/guests/show.html.erb
<div class="row">
  <div class="col-md-3">
    <p><%= @guest.name %></p>
  </div>
  <div class="col-md-4">
    <p><%= @guest.email %></p>
  </div>
  <div class="col-md-3">
    <p><%= link_to "Delete", event_guest_path(@event, @guest), method: "delete",  data: {confirm: "Are you sure?"} %></p>
  </div>

</div>