config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/edit'

  get 'events/update'

  get 'events/delete'

  devise_for :users, controllers: { sessions: "users/sessions" }, :skip => :registrations
  
  
  root to: "events#index"
  resources :events do
    member do
      get 'page'
      get 'edit_page'
    end

    resources :guests do
      member do
        get 'invite'
        post 'create_invite'
      end
    end
    resources :rsvps, except: [ :index ]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  has_one :client, class_name: "User"
  has_one :response, class_name: "Rsvp"
  
  has_many :listed_guests, class_name: "EventGuest",
                          foreign_key: "event_id",
                          dependent: :destroy
  has_many :guests, through: :listed_guests, source: "guest"


  def add_guest(user)
    listed_guests.create(guest_id: user.id)
  end
  
  def remove_guest(user)
    listed_guests.find_by(guest_id: user.id).destroy
  end
  
  def guest?(user)
    guests.include?(user)
  end
  
  def total_invited
    total = 0
    guests.each { |g| total += g.number_of_guests  }
    total
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :load_event, only: [ :create ]
  load_and_authorize_resource

  def index
    @events = Event.all
  end

  def show
    @guests = @event.guests
  end

  def new
    # @event = Event.new
    unauthorized! if cannot? :create, @event
  end

  def create
    # @event = Event.new(event_params)
    @event.update_attributes(event_params)
    if @event.save
      redirect_to @event
    else
       render :action => "new"
      # flash[:alert] = "Error updating the event"
    end
  end
  
  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to @event
    else
       render :action => "edit"
       flash[:alert] = "Error updating the event"
    end
  end

  def destroy
    if @event.delete
      redirect_to root_path
    end
  end
  def edit_page
    
  end
  def page
    
  end
  private
  
  def event_params
    params.require(:event).permit(:name, :description, :content)
  end

  def load_event
    @event = Event.new(event_params)
  end  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.description %></td>
  <td><%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/events/_event_form.html.erb
<%= render 'layouts/errors', object: @event %>
<%= form_for @event do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Name", class: "col-sm-3" %>
    <%= f.text_field :name, class: "col-sm-6" %>
  </div>
  <div class="form-group row">
    <%= f.label :description, "Description", class: "col-sm-3" %>
    <%= f.text_area :description, lines: 12, class: "col-sm-6" %>
  </div>
  <%= f.submit "Save", :disable_with => 'Saving...' %>
<% end %>  

app/views/events/_page_editor.html.erb
<%= form_for @event do |f| %>
  <%= f.text_area :content %>
  <%= f.submit "Save", disable_with: 'Saving...' %>
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit Event</h1>
    <%= render 'events/event_form' %>
  </div>
</div>

app/views/events/edit_page.js.erb
$("#page-content").html('<%= escape_javascript(render partial: "events/page_editor") %>');

app/views/events/index.html.erb
<h1>
    Events
    <small><%= link_to 'Create', new_event_path %></small>
</h1>
<table class="table">
    <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render @events %>
    </tbody>
</table>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create Event</h1>
    <%= render 'events/event_form' %>
  </div>
</div>

app/views/events/page.html.erb
    <div class="page-content" id="page-content">
      <div class="row">
        <div class="col-md-10 col-offset-md-1">
          <div class="page-header-background center-block">
              <div class="page-header"></div>     

          </div>
          <%= markdown(@event.content) %>
        </div>
    </div>
  </div>

app/views/events/show.html.erb
<div id="event-details">
    <h1>
        <%= @event.name %>
        <small><%= link_to 'Edit', edit_event_path(@event) %></small>
    </h1>
    <h3><%= @event.description %></h3>
</div>

<div class="guest-list">
    <h2>Guests</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Guest Names</th>
                <th>Email</th>
                <th>Postal Address</th>
                <th>No. Invited</th>
                <th class="text-center">RSVP'd?</th>
                <th class="text-center">No. Confirmed</th>
                <th><%= link_to "Add guest", new_event_guest_path(@event) %></th>
            </tr>
        </thead>
        <tbody>
            <%= render partial: 'guests/guests', collection: @guests, as: :guest %>
        </tbody>
    </table>
    <p>Number of invitations: <strong><%= @event.guests.count %></strong></p>
    <p>Number of invited guests: <strong><%= @event.total_invited %></strong></p>
    <p>Number of RSVP's:<strong></strong></p>
    <p>Number of confirmed guests:<strong></strong></p>
    
</div>
<% if !@event.response.nil? %>
    <div class="rsvp">
        <h2>RSVP</h2>
        
    
    </div>
<% end %>
<!--<h2>Page Content-->
<!--    <small><%= link_to 'Edit', edit_page_event_path(@event), remote: true %></small>-->
<!--    <small><%= link_to 'Show', page_event_path(@event) %></small>-->
<!--</h2>-->

<!--<div class="row">-->
<!--    <div class="page-content col-xs-12" id="page-content">-->
<!--        <div class="page-header-background center-block">-->
<!--            <div class="page-header"></div>        -->
<!--        </div>-->
<!--        <%= markdown(@event.content) %>-->
<!--    </div>-->
<!--</div>-->